### PR TITLE
Editing whitelist/list

### PR DESCRIPTION
**Pull request by alazymeme**
Just noticed that amazeful is being used as a bot in #pokimane and lurks in many other channels (likely to get subs). Also looks like the user has made a logging bot.

### CODE REVIEW

**Comment by MrEliasen** [comment]
You mentioned here https://github.com/MrEliasen/twitch-bot-list/issues/12 that amazeful was chatterino, and amazefullogger is the new logger bot? Or was the bot renamed?

**Comment by alazymeme** [comment]
No amazeful is an actual user, but it seems that it's also used as a bot accounts. I think it should go back on the list. amazefullogger is a separate account, that I guess is used for logging.

**Comment by MrEliasen** [comment]
In that case I would rather  add both to the list, since we don't know if amazefullogger is even a helpful service or similar like overrustlelogs.

no?

**Comment by alazymeme** [comment]
As in add both to the whitelist? Or revert amazeful and put the logger on the normal bot list? Keep in mind that amazeful is used as an actual bot in pokimane's channel:

image

**Comment by MrEliasen** [comment]
I think I have found the bot: https://amazeful.herokuapp.com/
Assuming that is the case, amazeful should be left on the whitelist I think.

No information found about amazefullogger from a quick google search, so grey listing it is probably wise for now.

Thoughts?

**Comment by alazymeme** [comment]
Ok this sounds good

**Comment by alazymeme** [comment]
done

**Pull request merged**
